### ISSUE TITLE
handle QR Code scanner

### ISSUE THREAD

**Issue by alberanid** [raspibo/eventman#33]
A QR Code scanner (a separated process or daemon) will be used to mark persons as attendees.

A new controller is needed to manage this workflow.

See the https://github.com/raspibo/event_man project.

**Comment by dcast78** [comment]
To proced with integration we need to define spedifications  for data exchange:
possibile formats

http://serveraddr:port/events/12345678/persons/98765432
where 
12345678 =id of event
98765432 = id of attendant

with put request and minimum fields to handle update
{"person": {"person_id": "98765432", "attended": 1, "datetime" : "2015-04-14T22:00:00.000Z","op_detail": "checkin"}}
 person_id = barcode attendant identificator

or with only url format

http://serveraddr:port/events/12345678/persons/98765432/attended/1/datetime/201504-4T220000000Z/op_detail/checkin

To solve this question we need an option from web devloper.

**Comment by alberanid** [comment]
For sure every update operation on a registered person must be a **PUT** request to the **http://serveraddr:port/events/$eventID/persons/$personID** url.

The passed data must be valid (serialized) JSON.  See #35 for an example using _curl_.

For the content: while I'd like to store everything in some sort of history of how a person interacted with an event (registered, attended, leaved, re-entered and so on) I don't think there's time to develop the required GUI and backend.

So, let's start with the simpler option: setting some parameters in the person's entry in the list of persons registered at an event.

To be more generic, we need something more than the ability to update a person with a known ID: after all, scanning a QR Code we know the QR Code, not the personID (which is a unique value generated by MongoDB).
So, I've introduced the ability to use **PUT** on the **http://serveraddr:port/events/$eventID/persons/** url specifying a query.

For example:

```
curl -X PUT -H "Content-Type: application/json" -d '{"attended": true, "checkin_datetime": "2015-04-14T22:00:00.000Z"}' http://localhost:5242/events/552ac6e8dff0d739cad1c4d0/persons/?name=Pippo
```

Will set the _attended_ and _checkin_datetime_ for the first entry in the list of persons registered at event 552ac6e8dff0d739cad1c4d0 whose _name_ is **Pippo**.

So, provided that we've previously imported a list of attendees containing the _ebqrcode_ (from a CSV file), we can do something like:

```
curl -X PUT -H "Content-Type: application/json" -d '{"attended": true, "checkin_datetime": "2015-04-14T22:00:00.000Z"}' http://localhost:5242/events/552ac6e8dff0d739cad1c4d0/persons/?ebqrcode=191659281
```
